kind: pipeline
type: docker
name: default
   
steps:
  - name: install
    image: node:18
    commands:
      - npm install

  - name: build
    image: node:18
    commands:
      - npm run build
    when:
      branch:
      - main
      - dev
      event:
      - pull_request
      - push

  - name: build-lib
    image: node:18
    commands:
      - npm run build:lib
    when:
      event:
      - tag

  - name: test
    image: node:18
    commands:
      - npm run test
    when:
      branch:
      - main
      - dev

  - name: docs
    image: node:18
    commands:
      - npm run docs:production
    when:
      branch:
      - main
      - dev 

  - name: types
    image: node:18
    commands:
      - npm run build:types
      - npm run api:extract
    when:
      event:
      - tag

  - name: overwrite_gitignore
    image: node:18
    commands:
      - echo "node_modules\ntemp" > .gitignore
    when:
      branch:
      - main
      event:
      - push

  - name: publish
    image: plugins/gh-pages
    settings:
      username:
         from_secret: github_username
      password:
         from_secret: github_token
      pages_directory: .
      copy_contents: true
      force_push: true
    when:
      branch:
      - main
      event:
      - push

  - name: npm
    image: plugins/npm
    settings:
      token: 
        from_secret: npm_token
      email: 
        from_secret: npm_email
    when:
      event:
      - tag

