kind: pipeline
type: docker
name: default
   
steps:
  - name: install
    image: node:18
    commands:
      - npm install

  - name: build
    image: node:18
    commands:
      - npm run build
    when:
      branch:
      - main
      - dev

  - name: test
    image: node:18
    commands:
      - npm run test
    when:
      branch:
      - main
      - dev

  - name: docs
    image: node:18
    commands:
      - npm run docs:production
    when:
      branch:
      - main
      - dev 

  - name: publish
    image: appleboy/drone-git-push
    settings:
      remote: https://github.com/nytimes/three-loader-3dtiles.git
      branch: gh-pages
      commit : true
      force: true
    environment:
      GITHUB_PASSWORD:
        from_secret: github-token
      GITHUB_USERNAME:
        from_secret: github-username
    when:
      branch:
      - dev
      event:
      - push

  - name: npm
    image: plugins/npm
    settings:
      token: 
        from_secret: npm_token
      email: 
        from_secret: npm_email
    when:
      event:
      - tag

