kind: pipeline
type: docker
name: default
   
steps:
  - name: install
    image: node:18
    commands:
      - npm install

  - name: build
    image: node:18
    commands:
      - npm run build
    when:
      branch:
      - main
      - dev

  - name: build-npm
    image: node:18
    commands:
      - npm run build
    when:
      event:
      - tag

  - name: test
    image: node:18
    commands:
      - npm run test
    when:
      branch:
      - main
      - dev

  - name: docs
    image: node:18
    commands:
      - npm run docs:production
    when:
      branch:
      - main
      - dev 

  - name: publish
    image: plugins/gh-pages
    settings:
      username: 
        from_secret: github_username
      ssh_key:
        from_secret: github_ssh_key
    when:
      branch:
      - dev

  - name: npm
    image: plugins/npm
    settings:
      token: 
        from_secret: npm_token
      email: 
        from_secret: npm_email
    when:
      event:
      - tag

